// Generated by `pnpm zenodo:collection --prod --publish` (TASK-23.09).
// The umbrella DOI for Ben Swift's live-coding body of work + its Zenodo
// Community. Cite the conceptDoi — it is stable as gigs are appended.

export interface LivecodingCollection {
  doi: string;
  conceptDoi: string;
  doiUrl: string;
  community: { slug: string; url: string };
}

export const livecodingCollection: LivecodingCollection | null = {
  doi: "10.5281/zenodo.20743615",
  conceptDoi: "10.5281/zenodo.20743614",
  doiUrl: "https://doi.org/10.5281/zenodo.20743614",
  community: {
    slug: "ben-swift-livecoding",
    url: "https://zenodo.org/communities/ben-swift-livecoding",
  },
};
